sources:
  - repo: "savannahostrowski/pyperf_bench" # Repository to fetch benchmark data from
    fork_filter: "python" # New field to specify which fork to filter by (default is "python")
    machines:
      blueberry: # Machine identifier
        description: "Raspberry Pi 5, 8GB RAM"
        os: "Raspbian GNU/Linux 12 (bullseye)"
        arch: "aarch64"
        color: "#a855f7"
      ripley:
        description: "Raspberry Pi 5, 8GB RAM"
        os: "Raspbian GNU/Linux 12 (bullseye)"
        arch: "aarch64"
        color: "#a855f7"